### ISSUE TITLE
arrows for choosing greeting cards needs css attention

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/AleyDafna-Shop#16] opened 2016-04-27 18:19 UTC
![image](https://cloud.githubusercontent.com/assets/18681483/14863263/a9c109e8-0cbd-11e6-8096-bf290600d05c.png)

**Comment by MeanEYE** [comment] 2016-05-01 07:56
Duplicate of #15.

**Closed as completed** 2016-05-01 07:56 UTC
Labels: duplicate
